dist: xenial
language: scala
matrix:
  include:
  - env: SBT_VERSION="1.2.8"
    jdk: openjdk8
  - env: SBT_VERSION="1.2.8"
    jdk: openjdk11
  - env: SBT_VERSION="1.4.2"
    jdk: openjdk11
script:
  - sbt "^^ ${SBT_VERSION}" clean test scripted
  - sbt "^^ ${SBT_VERSION}" dependencyCheck
after_failure:
  - if [ -f target/scala-2.10/sbt-0.13/dependency-check-report.json ]; then cat target/scala-2.10/sbt-0.13/dependency-check-report.json; fi
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/launchers"
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
before_script:
  - rm -rf $HOME/.ivy2/cache/org.owasp/dependency-check-utils/jars/data
sudo: false
